#!/usr/bin/env bash
# Idempotent pod setup for qc-translate. Installs EVERYTHING under /workspace (the
# persistent network volume) so re-spinning a RunPod pod is fast. No Docker.
# Reuses anything the base image already provides (Python/torch/CUDA, and a system
# java/tesseract if present).
#
#   bash bootstrap.sh
#
set -euo pipefail

# ---- Pinned versions ---------------------------------------------------------
OKAPI_VERSION="${OKAPI_VERSION:-1.48.0}"
JAVA_FEATURE="${JAVA_FEATURE:-17}"           # Temurin JRE major version

# ---- Layout ------------------------------------------------------------------
WORKSPACE="${WORKSPACE:-/workspace}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS="$WORKSPACE/tools"
VENV="$WORKSPACE/venv"
HF_CACHE="$WORKSPACE/hf-cache"
ENV_FILE="$REPO_DIR/.env.runtime"            # sourced by serve.sh and the CLI

mkdir -p "$TOOLS" "$HF_CACHE" "$WORKSPACE/jobs" "$WORKSPACE/tm"

log() { printf '\033[1;34m[bootstrap]\033[0m %s\n' "$*"; }

# ---- 1. Python venv + deps ---------------------------------------------------
if [[ ! -x "$VENV/bin/python" ]]; then
  log "Creating venv at $VENV"
  python3 -m venv "$VENV"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"
python -m pip install --quiet --upgrade pip
log "Installing project (base deps)"
pip install --quiet -e "$REPO_DIR"
# GPU/QE extras (vLLM, COMET, transformers). Torch already ships in the pod image.
log "Installing serve + qe extras (vLLM, COMET, transformers)"
pip install --quiet -e "$REPO_DIR[serve,qe]" || log "WARN: serve/qe extras failed; check CUDA/torch compatibility"

# ---- 2. Java (portable Temurin JRE, unless a system java exists) -------------
JDK_DIR="$TOOLS/jdk"
if command -v java >/dev/null 2>&1; then
  DETECTED_JAVA_HOME="$(dirname "$(dirname "$(readlink -f "$(command -v java)")")")"
  log "Reusing system java at $DETECTED_JAVA_HOME"
  JAVA_HOME="$DETECTED_JAVA_HOME"
elif [[ -x "$JDK_DIR/bin/java" ]]; then
  log "Reusing portable JRE at $JDK_DIR"
  JAVA_HOME="$JDK_DIR"
else
  log "Downloading Temurin JRE $JAVA_FEATURE to $JDK_DIR"
  mkdir -p "$JDK_DIR"
  ARCH="$(uname -m)"; case "$ARCH" in x86_64) JARCH=x64;; aarch64) JARCH=aarch64;; *) JARCH="$ARCH";; esac
  URL="https://api.adoptium.net/v3/binary/latest/${JAVA_FEATURE}/ga/linux/${JARCH}/jre/hotspot/normal/eclipse"
  curl -fsSL "$URL" -o /tmp/jre.tgz
  tar -xzf /tmp/jre.tgz --strip-components=1 -C "$JDK_DIR"
  rm -f /tmp/jre.tgz
  JAVA_HOME="$JDK_DIR"
fi

# ---- 3. Okapi (portable, Tikal CLI) -----------------------------------------
OKAPI_DIR="$TOOLS/okapi"
if [[ -x "$OKAPI_DIR/tikal.sh" ]]; then
  log "Reusing Okapi at $OKAPI_DIR"
else
  log "Downloading Okapi $OKAPI_VERSION to $OKAPI_DIR"
  mkdir -p "$OKAPI_DIR"
  # Okapi moved off Bitbucket (downloads there are now gated); official host is okapiframework.org.
  OKAPI_URL="https://okapiframework.org/binaries/main/${OKAPI_VERSION}/okapi-apps_gtk2-linux-x86_64_${OKAPI_VERSION}.zip"
  curl -fsSL "$OKAPI_URL" -o /tmp/okapi.zip
  unzip -q -o /tmp/okapi.zip -d "$OKAPI_DIR"
  rm -f /tmp/okapi.zip
  chmod +x "$OKAPI_DIR"/*.sh 2>/dev/null || true
fi

# ---- 4. Tesseract (system if present, else conda-forge via micromamba) -------
if command -v tesseract >/dev/null 2>&1; then
  TESSERACT_BIN="$(command -v tesseract)"
  log "Reusing system tesseract at $TESSERACT_BIN"
elif [[ -x "$TOOLS/micromamba/envs/ocr/bin/tesseract" ]]; then
  TESSERACT_BIN="$TOOLS/micromamba/envs/ocr/bin/tesseract"
  log "Reusing conda tesseract at $TESSERACT_BIN"
else
  log "Installing tesseract via micromamba (conda-forge) into $TOOLS/micromamba"
  export MAMBA_ROOT_PREFIX="$TOOLS/micromamba"
  if [[ ! -x "$TOOLS/micromamba/bin/micromamba" ]]; then
    mkdir -p "$TOOLS/micromamba/bin"
    curl -fsSL https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xj -C "$TOOLS/micromamba" bin/micromamba
  fi
  "$TOOLS/micromamba/bin/micromamba" create -y -q -n ocr -c conda-forge tesseract >/dev/null
  TESSERACT_BIN="$TOOLS/micromamba/envs/ocr/bin/tesseract"
fi

# ---- 5. Write runtime env file ----------------------------------------------
log "Writing $ENV_FILE"
cat > "$ENV_FILE" <<EOF
# Auto-generated by bootstrap.sh — source this before running the pipeline.
export JAVA_HOME="$JAVA_HOME"
export OKAPI_HOME="$OKAPI_DIR"
export TESSERACT_BIN="$TESSERACT_BIN"
export HF_HOME="$HF_CACHE"
export PATH="$JAVA_HOME/bin:$OKAPI_DIR:$(dirname "$TESSERACT_BIN"):$VENV/bin:\$PATH"
EOF

# ---- 6. Pre-download model weights (optional but recommended) ----------------
# shellcheck disable=SC1090
source "$ENV_FILE"
if [[ "${QC_SKIP_WEIGHTS:-0}" != "1" ]]; then
  log "Pre-downloading model weights to $HF_CACHE (set QC_SKIP_WEIGHTS=1 to skip)"
  python "$REPO_DIR/scripts/fetch_weights.py" || log "WARN: weight prefetch failed; will download lazily on first run"
fi

log "Done. Next: 'bash serve.sh start' then 'qc-translate run <input.docx>'"
